// Themed beginner vocabulary — the syllabus behind the Learn tab's vocabulary lessons.
//
// Generated by scripts/build-themes.mjs from the `beginner` section of
// scripts/data/core-overrides.json, which is where these sets are authored and where the
// dictionary builds already read them from. Do not edit either copy by hand.
//
//   language -> theme -> [word, ...]
//
// Words only. Glosses are resolved at runtime through the dictionary the client already
// fetches, so there is no second copy of them to go stale.
//
// 1050 words across es:21 fr:21 zh:21 ja:21 themes; 0 dropped as not being headwords.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/beginner-themes.json';

export const BEGINNER_THEMES = data as unknown as Record<string, Record<string, string[]>>;
