// Auto-generated by scripts/build-esdict.mjs — DO NOT EDIT BY HAND.
// Maps CEFR level (1 = A1 = easiest … 6 = C2 = hardest) to its word list.
//
// NOTE: unlike HSK_LEVELS and JLPT_LEVELS, which come from official published exam word
// lists, the CEFR publishes no such list. These bands are a FREQUENCY APPROXIMATION —
// lemmas ranked by OpenSubtitles corpus frequency, cut at the cumulative vocabulary sizes
// commonly cited for each tier. Useful as a study progression, not authoritative.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/cefr-levels.json';

export const CEFR_LEVELS = data as unknown as Record<number, string[]>;
