// Auto-generated by scripts/build-esdict.mjs — DO NOT EDIT BY HAND.
// Inflected Spanish form → dictionary (lemma) form, sourced from Spanish Wiktionary's
// own `form_of` senses, so irregulars (fui → ser, voy → ir) are correct by construction.
// Scoped to forms that appear in the OpenSubtitles 50k frequency list — shipping the full
// conjugation table for every verb would be far larger than it is worth. Forms outside
// this set fall back to the suffix rules in lib/server/spanishLemmatizer.ts.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/es-forms.json';

export const ES_FORMS = data as unknown as Record<string, string>;
