// Spanish inflection table — which grammatical slot each form fills.
//
// Generated by scripts/build-esgrammar.mjs from the Spanish Wiktionary extract at kaikki.org
// (CC BY-SA 4.0), the same source scripts/build-esdict.mjs reads. See ATTRIBUTION.md.
//
//   { c: grammar codes, w: form -> [[codeIndex, lemma], ...] }
//
// A code is "pos|tag,tag,tag" with the tags sorted, e.g. "verb|imperfect,indicative,singular".
// Unlike the French table these are semantic tags rather than positional codes, so there is no
// slot ordering to get wrong. The lemma is stored so a lookup can require it to match the
// token's own baseForm: `casas` is a form of both `casa` and `casar`.
//
// Tags are raw; lib/spanishGrammar.ts turns them into English at render time so the wording
// can change without regenerating this file.
//
// 132,900 forms, 149,206 readings, 131 distinct codes, from 809,603 lines.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/es-grammar.json';

export const ES_GRAMMAR = data as unknown as { c: string[]; w: Record<string, [code: number, lemma: string][]> };
