// Auto-generated by scripts/build-esdict.mjs — DO NOT EDIT BY HAND.
//
// SURFACES THIS APP DOES NOT TREAT AS VOCABULARY, from the `nameCollision` section of
// scripts/data/core-overrides.json. Their corpus frequency belongs to a PERSON and their
// dictionary gloss to a rare homonym — `maría` is banded on every María in the news and
// glossed "magpie", `jesús` on every Jesús and glossed "bless you (after a sneeze)".
//
// Dropping them from the bands is only half the fix and the measurement proved it: an
// unbanded surface that still HAS a dictionary entry reads as "in no band at all", which
// `calculateReadability` counts as above level exactly like a C2 word. Re-measured on six
// A1 passages, `maría` simply moved from `B1×5` to `—×5` and the figure did not shift by
// a thousandth. So the metric has to EXCLUDE them, which is what `ungradeable` is for.
//
// One fact in one file: the same list drives the band removal and this exclusion, so they
// cannot drift. The words stay in esdict.json — tapping one still answers "magpie".
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/es-notvocab.json';

export const ES_NOT_VOCAB = data as unknown as string[];
