// Auto-generated by scripts/build-frdict.mjs — DO NOT EDIT BY HAND.
// Inflected French form → dictionary (lemma) form, sourced from French Wiktionary's own
// `form_of` senses, so irregulars (suis → être, ai → avoir) are correct by construction.
// Scoped to forms that clear the blended cross-register frequency ranking — shipping the full
// conjugation table for every verb would be far larger than it is worth. Forms outside
// this set fall back to the suffix rules in lib/server/frenchLemmatizer.ts.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/fr-forms.json';

export const FR_FORMS = data as unknown as Record<string, string>;
