// French inflection table — which grammatical slot each form fills.
//
// Generated by scripts/build-frgrammar.mjs from Lexique 3 (CC BY-SA 4.0), which is vendored
// at scripts/data/Lexique383.tsv for frequency ranking. See ATTRIBUTION.md.
//
//   { c: grammar codes, w: form -> [[codeIndex, lemma], ...] }
//
// A code is "POS|slots|gender|number", e.g. "VER|ind:imp:3s||" or "ADJ||f|s". Slots are every
// reading Lexique lists for the form, not the first — see the build script on why that matters.
// The lemma is stored so a lookup can require it to match the token's own baseForm, since the
// two come from different sources.
//
// Codes are raw; lib/frenchGrammar.ts turns them into English at render time so the wording
// can change without regenerating this file.
//
// 86,293 forms, 95,285 readings, 159 distinct codes, from 142,694 Lexique rows.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/fr-grammar.json';

export const FR_GRAMMAR = data as unknown as { c: string[]; w: Record<string, [code: number, lemma: string][]> };
