// Auto-generated by scripts/build-frdict.mjs — DO NOT EDIT BY HAND.
// Maps CEFR level (1 = A1 = easiest … 6 = C2 = hardest) to its word list.
//
// NOTE: unlike HSK_LEVELS and JLPT_LEVELS, which come from official published exam word
// lists, the CEFR publishes no such list. These bands are a FREQUENCY APPROXIMATION —
// lemmas ranked by Lexique 3's dual-register frequency — scored on the SMALLER of its film
// and book counts, so a word has to be common in both — and cut at the cumulative
// vocabulary sizes commonly cited for each tier. Headwords whose every sense is slang,
// vulgar, obsolete or dialectal are excluded outright. Useful as a study progression, not
// authoritative.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/fr-levels.json';

export const FR_LEVELS = data as unknown as Record<number, string[]>;
