// Auto-generated by scripts/build-frdict.mjs — DO NOT EDIT BY HAND.
// CEFR A1–C2 vocabulary (source: French Wiktionary glosses, banded by OpenSubtitles
// frequency — see the caveat in cefr-levels.ts about these bands being approximate).
// 'reading' exists only to match the shape of HSK_VOCAB / JLPT_VOCAB and is always ''
// for French, which has no pinyin/furigana analogue.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/fr-vocab.json';

export const FR_VOCAB = data as unknown as Record<string, { reading: string; meaning: string }>;
