// Auto-generated by scripts/reorder-glosses.mjs — DO NOT EDIT BY HAND.
//
// Headwords whose bundled definition was replaced after release. lib/deckGloss.ts re-syncs
// deck cards for exactly these words, because a card holding the old value cannot otherwise
// be told apart from one the learner rewrote themselves.
//
// The cost of being on this list: if you HAD hand-edited one of these few dozen words, your
// wording is replaced once. That trade only holds because the list is small and named.
export const REVISED_GLOSSES: Record<string, string[]> = {
  es: ["a", "abierta", "antiguos", "basada", "blanca", "chica", "corta", "cubana", "directa", "extraña", "fría", "maestra", "mala", "mexicana", "mía", "novia", "prima", "primera", "privada", "rara", "rica", "roja", "santa", "segunda", "suprema", "tercera", "tía", "vieja"],
};
