// Auto-generated by scripts/build-radicals.mjs — DO NOT EDIT BY HAND.
// Han character decomposition for the Chinese and Japanese readers.
//   g  short gloss          p  component characters, in reading order
//   r  radical              h  human-readable etymology hint
//   t  etymology type (ideographic | pictophonetic | pictographic)
//   ph phonetic component   se semantic component  (pictophonetic only)
//
// Derived from makemeahanzi's dictionary.txt (Unihan + CJKlib), LGPL v3 — see
// scripts/data/ATTRIBUTION.md. Scoped to characters used by HSK and JLPT vocabulary plus,
// transitively, every component those characters are built from.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/han-decomp.json';

export const HAN_DECOMP = data as unknown as Record<string, { g: string; p?: string; r?: string; h?: string; t?: string; ph?: string; se?: string }>;
