// Auto-generated by scripts/build-jmdict.mjs — DO NOT EDIT BY HAND.
// JLPT N5–N1 vocabulary (source: elzup/jlpt-word-list, derived from the Tanos lists).
// 'reading' is hiragana (or katakana for loanwords), the Japanese analogue of pinyin.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/jlpt-vocab.json';

export const JLPT_VOCAB = data as unknown as Record<string, { reading: string; meaning: string }>;
