// Auto-generated by scripts/build-jmdict.mjs — DO NOT EDIT BY HAND.
// Maps JLPT level (5 = N5 = easiest … 1 = N1 = hardest) to its word list.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/jlpt-levels.json';

export const JLPT_LEVELS = data as unknown as Record<number, string[]>;
