// GENERATED by scripts/build-lesson-practice.ts — do not edit.
//
// Sentences are authored in scripts/data/lesson-practice.json; the tiles here are cut by the
// REAL segmenters, so a puzzle's pieces fall exactly where the reader's word boundaries do.
// Regenerate with: npm run build:practice
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/lesson-practice.json';

export const LESSON_PRACTICE = data as unknown as Record<string, Record<string, { text: string; gloss: string; tiles: string[] }[]>>;
