// One idiom or proverb per language, for the daily proverb card.
//
// Chinese is DERIVED from CC-CEDICT's "(idiom)" entries, filtered to those a learner can
// read (every character in HSK) and ordered canon-first. Japanese, Spanish and French are
// curated in scripts/data/proverbs-seed.json and validated against their own dictionaries,
// because their emitted tables drop the upstream proverb tags.
//
// Generated by scripts/build-proverbs.mjs — do not edit by hand.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/proverbs.json';

export const PROVERBS = data as unknown as Record<string, { t: string; r?: string; m: string; l?: string; lv?: number }[]>;
