// Auto-generated by scripts/build-kodic.mts — DO NOT EDIT BY HAND.
// Maps TOPIK level (1 = easiest … 6 = hardest) to its word list.
// TOPIK I covers levels 1–2; TOPIK II covers 3–6.
//
// NOTE: unlike HSK_LEVELS and JLPT_LEVELS, which come from official published exam word
// lists, TOPIK publishes no such list — the same situation as CEFR_LEVELS. These bands are
// a FREQUENCY APPROXIMATION: headwords ranked by frequency BLENDED ACROSS THREE REGISTERS
// (Tatoeba / Global Voices / Wikimedia, median ipm, so a surface must be common in at least
// two of them) after lemmatizing the corpus, since Korean surface forms are overwhelmingly
// inflected, and cut at the cumulative vocabulary sizes commonly cited per level. Headwords
// whose every sense is slang, vulgar, obsolete or dialectal are excluded outright. Useful
// as a study progression, not authoritative.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/topik-levels.json';

export const TOPIK_LEVELS = data as unknown as Record<number, string[]>;
