// Auto-generated by scripts/build-kodic.mts — DO NOT EDIT BY HAND.
// TOPIK 1–6 vocabulary (source: Korean Wiktionary glosses, banded by blended cross-register
// corpus frequency — see the caveat in topik-levels.ts about these bands being approximate).
// 'reading' exists only to match the shape of HSK_VOCAB / JLPT_VOCAB / CEFR_VOCAB and is
// always '' for Korean: Hangul is phonetic and needs no separate reading line.
//
// The data lives in the sibling .json file, not as a TypeScript object literal, and is
// imported through the @data alias so TypeScript never opens it — see
// scripts/lib/emitData.mjs and lib/data/json-modules.d.ts. Regenerate both together.
import data from '@data/topik-vocab.json';

export const TOPIK_VOCAB = data as unknown as Record<string, { reading: string; meaning: string }>;
