/**
 * Emit the themed beginner vocabulary sets for the Learn tab.
 *
 * The syllabus ALREADY EXISTS. `scripts/data/core-overrides.json` carries a `beginner` section
 * of ~300 words per language in 21 themed sets — numbers, colours, weekdays, family, food,
 * house… — written because no corpus contains a beginner's world (see CLAUDE.md: fork,
 * Thursday, purple and yogurt ranked C1–C2). CLAUDE.md notes outright that the grouping is
 * kept rather than flattened "because it is a syllabus, and a study-by-topic feature wants
 * exactly that shape". This is that feature, so it reads the same file rather than restating
 * three hundred words in a second place that can drift.
 *
 * WORDS ONLY, NO GLOSSES. The client already fetches the full dictionary for the language it
 * is studying, so shipping definitions here would be a second copy of them — and the one that
 * goes stale when the dictionary is rebuilt. The Learn tab resolves each word through
 * `lookupReading` exactly as every other surface does.
 *
 * Every word is validated against the built dictionary and dropped with a warning if it does
 * not resolve, for the same reason the starter texts are: a vocabulary lesson that adds a card
 * with no definition on it is worse than one that omits the word.
 *
 * Usage: node scripts/build-themes.mjs   (after build-frdict / build-esdict)
 */
import { readFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { emitData } from './lib/emitData.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OVERRIDES = path.join(__dirname, 'data', 'core-overrides.json');
const OUT = path.join(__dirname, '..', 'lib', 'data', 'beginner-themes.ts');

/**
 * Where each language's built dictionary and level vocab live.
 *
 * zh and ja are here for the Learn tab ONLY. Their `beginner` sets cannot reach a level table:
 * `applyCoreOverrides` is called from build-esdict and build-frdict alone, and the HSK/JLPT
 * tables are checked-in data with no generator. That separation matters — CEFR bands are a
 * frequency approximation this repo derives and may re-pin, while HSK and JLPT are published
 * exam vocabulary, and forcing a word into HSK 1 would corrupt an authoritative list.
 */
const SOURCES = {
  es: { dict: 'public/esdict.json', vocab: 'lib/data/cefr-vocab.json' },
  fr: { dict: 'public/frdict.json', vocab: 'lib/data/fr-vocab.json' },
  zh: { dict: 'public/cedict.json', vocab: 'lib/data/hsk-vocab.json' },
  ja: { dict: 'public/jmdict.json', vocab: 'lib/data/jlpt-vocab.json' },
};

async function loadKeys(lang) {
  const src = SOURCES[lang];
  if (!src) return null;
  const keys = new Set();
  for (const rel of [src.dict, src.vocab]) {
    try {
      const raw = JSON.parse(await readFile(path.join(__dirname, '..', rel), 'utf8'));
      for (const k of Object.keys(raw)) keys.add(k);
    } catch {
      console.warn(`  ! could not read ${rel} — run its build script first`);
    }
  }
  return keys;
}

async function main() {
  const overrides = JSON.parse(await readFile(OVERRIDES, 'utf8'));
  const beginner = overrides.beginner ?? {};

  /** @type {Record<string, Record<string, string[]>>} */
  const out = {};
  let kept = 0, dropped = 0;

  for (const lang of Object.keys(beginner)) {
    const known = await loadKeys(lang);
    if (!known) { console.warn(`  ! no dictionary configured for ${lang}, skipping`); continue; }
    out[lang] = {};
    for (const [theme, words] of Object.entries(beginner[lang])) {
      const good = [];
      for (const w of words) {
        if (known.has(w)) { good.push(w); kept++; }
        else { console.warn(`  - ${lang}/${theme}: "${w}" is not a headword, dropped`); dropped++; }
      }
      if (good.length) out[lang][theme] = good;
    }
  }

  const themes = Object.entries(out).map(([l, t]) => `${l}:${Object.keys(t).length}`).join(' ');

  await emitData(
    OUT,
    'BEGINNER_THEMES',
    'Record<string, Record<string, string[]>>',
    out,
    `// Themed beginner vocabulary — the syllabus behind the Learn tab's vocabulary lessons.
//
// Generated by scripts/build-themes.mjs from the \`beginner\` section of
// scripts/data/core-overrides.json, which is where these sets are authored and where the
// dictionary builds already read them from. Do not edit either copy by hand.
//
//   language -> theme -> [word, ...]
//
// Words only. Glosses are resolved at runtime through the dictionary the client already
// fetches, so there is no second copy of them to go stale.
//
// ${kept} words across ${themes} themes; ${dropped} dropped as not being headwords.`,
  );

  console.log(`Wrote ${OUT}`);
  console.log(`  ${kept} words kept, ${dropped} dropped, themes per language: ${themes}`);
}

main().catch(err => { console.error(err); process.exit(1); });
