import { test } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { emitData } from './lib/emitData.mjs';
import { segmentFr } from '@/lib/server/frenchSegmenter';
import { segmentEs } from '@/lib/server/spanishSegmenter';
import { segmentZh } from '@/lib/server/chineseSegmenter';
import { segmentJa } from '@/lib/server/kuromojiSegmenter';
import { needsSpaceBefore } from '@/lib/tokenText';
import type { PassageToken } from '@/lib/types';

/**
 * Turns the authored practice sentences into tiles, using the REAL segmenters.
 *
 * ── WHY THIS IS GENERATED AND NOT WRITTEN ──
 * A build-the-sentence puzzle is only honest if its pieces fall where the reader's own word
 * boundaries fall. Every segmenter in this app is server-side, so the Learn tab cannot cut a
 * sentence itself; the tiles have to be checked in. Cutting them by hand across 306 sentences
 * in four languages would put a different set of boundaries in the exercise from the one the
 * reader meets in a passage — subtly, and only in the languages where it matters most.
 *
 * ── WHERE A TILE BOUNDARY IS ──
 * Exactly where a SPACE would go, which `lib/tokenText.ts` already decides for the whole app.
 * That is not a convenience: it is the same rule the passage renderer, the cloze sentence and
 * the TTS plaintext use, so a tile row cannot disagree with the rest of the app about whether
 * `¿` belongs to the word after it or the `?` to the word before. Chinese and Japanese take
 * no spaces at all, so there the rule is "one tile per word, punctuation rides along".
 *
 * Run with: npm run build:practice
 */

type Row = { text: string; gloss: string };
type Src = Record<string, Record<string, Row[]>>;

const UNSPACED = new Set(['zh', 'ja']);

/**
 * Segmenter output as PassageTokens.
 *
 * Punctuation is decided from the CHARACTERS, not from the tuple width, and Chinese is why:
 * `segmentZh` deliberately emits every token bare — a 1-tuple — for the client to resolve
 * against the dictionary, so "a 1-tuple is punctuation" is true of the other three languages
 * and false of that one. Reading the width put every Chinese word in the punctuation bucket
 * and folded whole sentences into a single tile, which is a puzzle with one piece.
 */
const NOT_A_WORD = /^[^\p{L}\p{N}]+$/u;

async function tokenize(lang: string, text: string): Promise<PassageToken[]> {
  const raw = lang === 'ja'
    ? await segmentJa(text, new Map())
    : (lang === 'zh' ? segmentZh : lang === 'fr' ? segmentFr : segmentEs)(text, new Map());
  return (raw as unknown as string[][]).map(t => ({
    text: t[0],
    ...(NOT_A_WORD.test(t[0]) ? { type: 'punct' as const } : {}),
  }));
}

function toTiles(tokens: PassageToken[], unspaced: boolean): string[] {
  const tiles: string[] = [];
  tokens.forEach((tok, i) => {
    // A new tile starts wherever a space would. In an unspaced script no space ever would,
    // so the rule there is one tile per WORD with punctuation folded into its neighbour —
    // which is what keeps a full stop off the end of the row as a tile of its own, where it
    // would answer the question by itself.
    const fresh = i === 0
      || (unspaced ? tok.type !== 'punct' : needsSpaceBefore(tokens, i, false) === ' ');
    if (fresh) tiles.push(tok.text);
    else tiles[tiles.length - 1] += tok.text;
  });
  return tiles;
}

test('build lesson practice tiles', async () => {
  const root = resolve(import.meta.dirname, '..');
  const src: Src = JSON.parse(readFileSync(resolve(root, 'scripts/data/lesson-practice.json'), 'utf8'));

  const out: Record<string, Record<string, (Row & { tiles: string[] })[]>> = {};
  let n = 0;
  for (const [lang, lessons] of Object.entries(src)) {
    out[lang] = {};
    for (const [id, rows] of Object.entries(lessons)) {
      out[lang][id] = [];
      for (const row of rows) {
        const tiles = toTiles(await tokenize(lang, row.text), UNSPACED.has(lang));
        const rebuilt = tiles.join('').replace(/\s+/g, '');
        if (rebuilt !== row.text.replace(/\s+/g, '')) {
          throw new Error(`${id}: tiles do not rebuild «${row.text}» — got «${rebuilt}»`);
        }
        out[lang][id].push({ ...row, tiles });
        n++;
      }
    }
  }

  await emitData(
    resolve(root, 'lib/data/lesson-practice.ts'),
    'LESSON_PRACTICE',
    'Record<string, Record<string, { text: string; gloss: string; tiles: string[] }[]>>',
    out,
    `// GENERATED by scripts/build-lesson-practice.ts — do not edit.
//
// Sentences are authored in scripts/data/lesson-practice.json; the tiles here are cut by the
// REAL segmenters, so a puzzle's pieces fall exactly where the reader's word boundaries do.
// Regenerate with: npm run build:practice`,
  );
  console.log(`lesson-practice: ${n} sentences across ${Object.keys(src).length} languages`);
});
