#!/usr/bin/env node
/**
 * Builds the Japanese language data from public open-source datasets:
 *
 *   public/jmdict.json        — { surface: { p: reading(hiragana), m: meaning } }
 *                               the Japanese analogue of public/cedict.json. Used by
 *                               lib/data/jadict.ts for furigana + meaning lookup.
 *   lib/data/jlpt-vocab.ts    — JLPT_VOCAB: surface → { reading, meaning }
 *   lib/data/jlpt-levels.ts   — JLPT_LEVELS: level(1–5) → surface[]  (5 = N5 = easiest)
 *
 * Sources:
 *   - JMdict (common subset) via scriptin/jmdict-simplified (Creative Commons)
 *   - JLPT word lists via elzup/jlpt-word-list (derived from the Tanos lists)
 *
 * Run with: node scripts/build-jmdict.mjs
 * Requires `curl` and `tar` on PATH (same network assumption as build-cedict.mjs).
 */
import { execSync } from 'child_process';
import { writeFile, readFile, mkdtemp } from 'fs/promises';
import { tmpdir } from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const JMDICT_RELEASE = '3.6.2%2B20260629154100';
const JMDICT_FILE = 'jmdict-eng-common-3.6.2%2B20260629154100.json.tgz';
const JMDICT_URL = `https://github.com/scriptin/jmdict-simplified/releases/download/${JMDICT_RELEASE}/${JMDICT_FILE}`;
const JLPT_BASE = 'https://raw.githubusercontent.com/elzup/jlpt-word-list/master/src';

// ─── tiny CSV parser (handles quoted fields with commas) ─────────────────────
function parseCsv(text) {
  const rows = [];
  for (const line of text.split('\n')) {
    if (!line.trim()) continue;
    const cells = [];
    let cur = '', inQ = false;
    for (let i = 0; i < line.length; i++) {
      const c = line[i];
      if (inQ) {
        if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; }
        else if (c === '"') inQ = false;
        else cur += c;
      } else if (c === '"') inQ = true;
      else if (c === ',') { cells.push(cur); cur = ''; }
      else cur += c;
    }
    cells.push(cur);
    rows.push(cells);
  }
  return rows;
}

const cap = (s, n = 80) => (s.length > n ? s.slice(0, n - 1) + '…' : s);

// ─── JLPT lists → JLPT_VOCAB + JLPT_LEVELS ───────────────────────────────────
async function buildJlpt(workdir) {
  const vocab = {};                       // surface → { reading, meaning }
  const levels = { 1: [], 2: [], 3: [], 4: [], 5: [] };
  const assigned = new Set();             // each word lands in its easiest level only

  // Easiest first (N5=5 … N1=1) so a multi-level word keeps its beginner entry.
  for (const lvl of [5, 4, 3, 2, 1]) {
    const file = path.join(workdir, `jlpt-n${lvl}.csv`);
    execSync(`curl -sL -m 60 -o "${file}" "${JLPT_BASE}/n${lvl}.csv"`);
    const rows = parseCsv(await readFile(file, 'utf8'));
    for (const [expr, reading, meaning] of rows) {
      if (!expr || expr === 'expression') continue;
      const e = expr.trim();
      if (!vocab[e]) vocab[e] = { reading: (reading || '').trim(), meaning: cap((meaning || '').trim()) };
      if (!assigned.has(e)) { assigned.add(e); levels[lvl].push(e); }
    }
  }

  const vLines = Object.entries(vocab)
    .map(([k, v]) => `  ${JSON.stringify(k)}: { reading: ${JSON.stringify(v.reading)}, meaning: ${JSON.stringify(v.meaning)} },`)
    .join('\n');
  await writeFile(path.join(ROOT, 'lib/data/jlpt-vocab.ts'),
`// Auto-generated by scripts/build-jmdict.mjs — DO NOT EDIT BY HAND.
// JLPT N5–N1 vocabulary (source: elzup/jlpt-word-list, derived from the Tanos lists).
// 'reading' is hiragana (or katakana for loanwords), the Japanese analogue of pinyin.
export const JLPT_VOCAB: Record<string, { reading: string; meaning: string }> = {
${vLines}
};
`, 'utf8');

  const lvLines = [5, 4, 3, 2, 1]
    .map(l => `  ${l}: ${JSON.stringify(levels[l])},`)
    .join('\n');
  await writeFile(path.join(ROOT, 'lib/data/jlpt-levels.ts'),
`// Auto-generated by scripts/build-jmdict.mjs — DO NOT EDIT BY HAND.
// Maps JLPT level (5 = N5 = easiest … 1 = N1 = hardest) to its word list.
export const JLPT_LEVELS: Record<number, string[]> = {
${lvLines}
};
`, 'utf8');

  console.log(`JLPT: ${Object.keys(vocab).length} words — ` +
    [5, 4, 3, 2, 1].map(l => `N${l}=${levels[l].length}`).join(' '));
  return vocab;
}

// ─── JMdict common → public/jmdict.json ──────────────────────────────────────
async function buildJmdict(workdir, jlptVocab) {
  const jsonPath = path.join(workdir, 'jmdict.json');
  execSync(`curl -sL -m 180 "${JMDICT_URL}" | tar xz -O > "${jsonPath}"`, { shell: '/bin/bash' });
  const data = JSON.parse(await readFile(jsonPath, 'utf8'));

  const map = {};   // surface → { p, m }
  const prio = {};  // surface → priority (2 = from a common form, 1 = uncommon)
  const put = (surface, reading, meaning, p) => {
    if (!surface || !reading) return;
    if (map[surface] && (prio[surface] ?? 0) >= p) return;
    map[surface] = { p: reading, m: meaning };
    prio[surface] = p;
  };

  for (const w of data.words) {
    const senseGloss = (w.sense || [])
      .find(s => s.gloss && s.gloss.length);
    if (!senseGloss) continue;
    const meaning = cap(senseGloss.gloss.map(g => g.text).slice(0, 3).join('; '));

    const kana = w.kana || [];
    const primaryKana = kana.find(k => k.common) || kana[0];
    if (!primaryKana) continue;

    // Kanji forms: read with the kana that applies to them.
    for (const kj of (w.kanji || [])) {
      const match = kana.find(k =>
        (k.appliesToKanji?.includes('*') || k.appliesToKanji?.includes(kj.text)));
      const reading = (match || primaryKana).text;
      put(kj.text, reading, meaning, kj.common ? 2 : 1);
    }
    // Kana-written form resolves to itself.
    put(primaryKana.text, primaryKana.text, meaning, primaryKana.common ? 2 : 1);
  }

  // Guarantee every JLPT word resolves (fill gaps; JMdict readings win where present).
  let added = 0;
  for (const [surface, v] of Object.entries(jlptVocab)) {
    if (!map[surface] && v.reading) { map[surface] = { p: v.reading, m: v.meaning }; added++; }
  }

  const out = path.join(ROOT, 'public', 'jmdict.json');
  const json = JSON.stringify(map);
  await writeFile(out, json, 'utf8');
  console.log(`JMdict: ${Object.keys(map).length} surface forms (+${added} JLPT-only) — ${Math.round(json.length / 1024)} KB`);
}

async function main() {
  const workdir = await mkdtemp(path.join(tmpdir(), 'jmdict-'));
  console.log('workdir:', workdir);
  const jlptVocab = await buildJlpt(workdir);
  await buildJmdict(workdir, jlptVocab);
  console.log('Done.');
}

main().catch(err => { console.error(err); process.exit(1); });
